//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYFITNESSAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        [Display(Name = "Choose Existing Training Topic")]
        public int ScheduleTrainingTypeID { get; set; }
        public System.DateTime ScheduleDay { get; set; }
        public string ScheduleStartTime { get; set; }
        public string ScheduleEndTime { get; set; }



        public virtual TrainingType TrainingType { get; set; }
    }
}
