//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYFITNESSAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingType()
        {
            this.Schedule = new HashSet<Schedule>();
        }

        public int TrainingTypeID { get; set; }
        [Display(Name = "Training Topic")]
        public string TrainingName { get; set; }
        [Display(Name = "Training Description")]
        [DataType(DataType.MultilineText)]
        public string TrainingDesc { get; set; }
        public byte[] TrainingPhoto { get; set; }
        public Nullable<int> TrainingTrainerID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
