//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYFITNESSAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.TrainingType = new HashSet<TrainingType>();
        }

        public int TrainerID { get; set; }
        [Required(ErrorMessage = "You must provide a Full Name")]
        [Display(Name = "Trainer's Full Name")]
        public string TrainerFullName { get; set; }
        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string TrainerPhone { get; set; }
        [Required(ErrorMessage = "Please provide a valid e-mail address")]
        [Display(Name = "Trainer's e-mail address")]
        [StringLength(20)]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\S+@\S+$")]
        public string TrainerEmail { get; set; }
        [Display(Name = "Short Biography")]
        [DataType(DataType.MultilineText)]
        public string TrainerBio { get; set; }
        [Display(Name = "Upload Personal Photo")]
        public byte[] TrainerPhoto { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingType> TrainingType { get; set; }
    }
}
